//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foroshgahlebas.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class dress_factor
    {
        public int factorid { get; set; }
        public int dressid { get; set; }
        public int number { get; set; }
        public long payment { get; set; }
    
        public virtual dress dress { get; set; }
        public virtual factor factor { get; set; }
    }
}
