//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foroshgahlebas.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class dress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dress()
        {
            this.dress_factor = new HashSet<dress_factor>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public double size { get; set; }
        public string color { get; set; }
        public int producerid { get; set; }
        public int number { get; set; }
        public long payment { get; set; }
        public int typeid { get; set; }
    
        public virtual producer producer { get; set; }
        public virtual type type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dress_factor> dress_factor { get; set; }
    }
}
